### ISSUE TITLE
New example database

### ISSUE THREAD

**Issue by velf** [sscu-budapest/mobility#4]
Dear Guardian of Data aka Endre,

We (Sanyi, Adam, Orsi, Luis) would like to have a filtered database, preferably in a SQL (postgres) format based on the following conditions:

1. Keep only those users who have at least 80% of their  pings within this Budapest Bounding Box —> 
- top left:47.822061130940774, 18.820110819804505
- right bottom: 47.30231005304629, 19.463117434663303
2. users with at least min. 50 reliable days (a 'reliable' user day is a day where a user has at least 5 pings between 5 am and 10 am, and at least 5 pings between 4 pm and 8 pm)
3. at least 50 pings/ reliable day

Thanks!
O

**Comment by endremborza** [comment]
As I understand it correctly, this will result in 3 additional subsets for the data:

`mostly_budapest_users`, `over50_reliable_day_users`

but I'm afraid the complete specification for the 3rd is unclear. Is it all users who have at least one reliable day with 50 pings? or only the user days that are reliable and have over 50 pings? or something else?

**Comment by velf** [comment]
all three conditions must apply at the same time. SO out of the mostly Budapest users who have at least 50 reliable days where they have at least 50 pings.

**Comment by endremborza** [comment]
So also in the second subset, the Budapest filter applies still?

**Comment by velf** [comment]
yes, all 3 apply - we want a small dataset!

**Comment by endremborza** [comment]
So, after another correction I surmised that this is just one sample where all these conditions apply.

This reduced the ping count to about 382M so to ~12% of the original dataset. Still not very small :)

here is a small report of the 1st part: https://github.com/sscu-budapest/mobility/blob/into-project-template/reports/local_user_distribution.md - on the branch that does the heavy lifting

As the postgres access does not yet have a public version, I will share that on slack.

**Comment by endremborza** [comment]
As we have managed to make the postgres access work, closing this.
